package experimental_test

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"sync"
	"testing"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"
	"github.com/tetratelabs/wazero/experimental"
	"github.com/tetratelabs/wazero/internal/platform"
	"github.com/tetratelabs/wazero/internal/testing/binaryencoding"
	"github.com/tetratelabs/wazero/internal/testing/require"
	"github.com/tetratelabs/wazero/internal/wasm"
	"github.com/tetratelabs/wazero/internal/wasmruntime"
)

// yieldWasm was generated by the following:
//
//	cd testdata; wasm-tools parse yield.wat -o yield.wasm
//
//go:embed testdata/yield.wasm
var yieldWasm []byte

type engineConfig struct {
	name string
	cfg  wazero.RuntimeConfig
}

func engineConfigs() []engineConfig {
	return []engineConfig{
		{"interpreter", wazero.NewRuntimeConfigInterpreter()},
		{"compiler", wazero.NewRuntimeConfigCompiler()},
	}
}

type observingTimeProvider struct {
	nanotime func() int64
}

func newObservingTimeProvider() observingTimeProvider {
	return observingTimeProvider{nanotime: platform.NewFakeNanotime()}
}

func (p observingTimeProvider) Walltime() (int64, int32) { return 0, 0 }
func (p observingTimeProvider) Nanotime() int64          { return p.nanotime() }
func (p observingTimeProvider) Nanosleep(int64)          {}

type recordingYieldObserver struct {
	mu           sync.Mutex
	observations []experimental.YieldObservation
}

func (r *recordingYieldObserver) ObserveYield(_ context.Context, observation experimental.YieldObservation) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.observations = append(r.observations, observation)
}

func (r *recordingYieldObserver) snapshot() []experimental.YieldObservation {
	r.mu.Lock()
	defer r.mu.Unlock()
	return append([]experimental.YieldObservation(nil), r.observations...)
}

// yieldingHostFunc is a GoModuleFunction that yields execution.
type yieldingHostFunc struct{ t *testing.T }

func (f *yieldingHostFunc) Call(ctx context.Context, mod api.Module, stack []uint64) {
	yielder := experimental.GetYielder(ctx)
	if yielder == nil {
		f.t.Fatal("expected yielder in context")
	}
	yielder.Yield()
	// Unreachable after Yield().
}

func setupYieldTest(t *testing.T, cfg wazero.RuntimeConfig) (api.Module, wazero.Runtime, context.Context) {
	return setupYieldTestWithHost(t, cfg, &yieldingHostFunc{t: t})
}

func setupYieldTestWithHost(t *testing.T, cfg wazero.RuntimeConfig, host api.GoModuleFunction) (api.Module, wazero.Runtime, context.Context) {
	t.Helper()
	ctx := context.Background()
	rt := wazero.NewRuntimeWithConfig(ctx, cfg)

	_, err := rt.NewHostModuleBuilder("example").
		NewFunctionBuilder().
		WithGoModuleFunction(host,
			nil,                                // no params
			[]api.ValueType{api.ValueTypeI32}). // 1 i32 result
		Export("async_work").
		Instantiate(ctx)
	require.NoError(t, err)

	mod, err := rt.Instantiate(ctx, yieldWasm)
	require.NoError(t, err)

	return mod, rt, ctx
}

func setupYieldResultCountChangeTest(t *testing.T, cfg wazero.RuntimeConfig) (api.Module, wazero.Runtime, context.Context) {
	t.Helper()
	ctx := context.Background()
	rt := wazero.NewRuntimeWithConfig(ctx, cfg)

	builder := rt.NewHostModuleBuilder("example")
	builder.NewFunctionBuilder().
		WithGoModuleFunction(&yieldingHostFunc{t: t},
			nil,
			[]api.ValueType{api.ValueTypeI32}).
		Export("async_one")
	builder.NewFunctionBuilder().
		WithGoModuleFunction(&yieldingHostFunc{t: t},
			nil,
			[]api.ValueType{api.ValueTypeI32, api.ValueTypeI32}).
		Export("async_two")
	_, err := builder.Instantiate(ctx)
	require.NoError(t, err)

	mod, err := rt.Instantiate(ctx, yieldDifferentResultCountsWasm())
	require.NoError(t, err)

	return mod, rt, ctx
}

func requireYieldError(t *testing.T, err error) *experimental.YieldError {
	t.Helper()
	var yieldErr *experimental.YieldError
	require.True(t, errors.As(err, &yieldErr), "expected YieldError, got: %v", err)
	require.NotNil(t, yieldErr.Resumer())
	return yieldErr
}

func TestYield_BasicYieldAndResume(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)
			resumer := yieldErr.Resumer()

			results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.NoError(t, err)
			require.Equal(t, uint64(142), results[0]) // 42 + 100
		})
	}
}

func TestYield_ResumeFromDifferentGoroutine(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)

			var wg sync.WaitGroup
			var results []uint64
			var resumeErr error
			wg.Add(1)
			go func() {
				defer wg.Done()
				results, resumeErr = yieldErr.Resumer().Resume(experimental.WithYielder(ctx), []uint64{7})
			}()
			wg.Wait()

			require.NoError(t, resumeErr)
			require.Equal(t, uint64(107), results[0]) // 7 + 100
		})
	}
}

func TestYield_Cancel(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)
			resumer := yieldErr.Resumer()

			resumer.Cancel()
			resumer.Cancel() // idempotent

			_, err = resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.Error(t, err)
			require.Contains(t, err.Error(), "cancelled")
		})
	}
}

func TestYield_CancelDoesNotNotifyTrapObserver(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			observer := &recordingTrapObserver{}
			_, err := mod.ExportedFunction("run").Call(
				experimental.WithTrapObserver(experimental.WithYielder(ctx), observer),
			)

			resumer := requireYieldError(t, err).Resumer()
			resumer.Cancel()

			require.Zero(t, observer.count())

			_, err = resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.EqualError(t, err, "cannot resume: resumer has been cancelled")
			require.Zero(t, observer.count())
		})
	}
}

func TestYield_ResumeRejectsWrongHostResultCount(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			for _, tc := range []struct {
				name        string
				hostResults []uint64
			}{
				{name: "too few", hostResults: nil},
				{name: "too many", hostResults: []uint64{1, 2}},
			} {
				t.Run(tc.name, func(t *testing.T) {
					mod, rt, ctx := setupYieldTest(t, ec.cfg)
					defer rt.Close(ctx)

					_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
					resumer := requireYieldError(t, err).Resumer()

					_, err = resumer.Resume(experimental.WithYielder(ctx), tc.hostResults)
					require.EqualError(t, err, fmt.Sprintf("cannot resume: expected 1 host results, but got %d", len(tc.hostResults)))

					results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
					require.NoError(t, err)
					require.Equal(t, []uint64{142}, results)
				})
			}
		})
	}
}

func TestYield_ResumeRejectsNilContext(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			resumer := requireYieldError(t, err).Resumer()

			_, err = resumer.Resume(nil, []uint64{42})
			require.EqualError(t, err, "cannot resume: context is nil")

			results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.NoError(t, err)
			require.Equal(t, []uint64{142}, results)
		})
	}
}

func TestYield_ResumeRejectsClosedModule(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			resumer := requireYieldError(t, err).Resumer()

			require.NoError(t, mod.Close(ctx))

			_, err = resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.ErrorIs(t, err, api.NewExitError(0))
		})
	}
}

func TestYield_ReyieldUsesFreshResumer(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run_twice").Call(experimental.WithYielder(ctx))
			firstResumer := requireYieldError(t, err).Resumer()

			_, err = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{40})
			secondYield := requireYieldError(t, err)

			firstResumer.Cancel() // spent resumers must not interfere with the new suspended execution

			results, err := secondYield.Resumer().Resume(experimental.WithYielder(ctx), []uint64{2})
			require.NoError(t, err)
			require.Equal(t, []uint64{42}, results)

			panicErr := require.CapturePanic(func() {
				_, _ = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{1})
			})
			require.Error(t, panicErr)
			require.Contains(t, panicErr.Error(), "Resume called more than once")
		})
	}
}

func TestYield_ReyieldResumerStillUsableAfterValidationError(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run_twice").Call(experimental.WithYielder(ctx))
			firstResumer := requireYieldError(t, err).Resumer()

			_, err = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{40})
			secondResumer := requireYieldError(t, err).Resumer()

			_, err = secondResumer.Resume(nil, []uint64{2})
			require.EqualError(t, err, "cannot resume: context is nil")

			results, err := secondResumer.Resume(experimental.WithYielder(ctx), []uint64{2})
			require.NoError(t, err)
			require.Equal(t, []uint64{42}, results)
		})
	}
}

func TestYield_ReyieldUpdatesExpectedHostResultCount(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldResultCountChangeTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			firstResumer := requireYieldError(t, err).Resumer()

			_, err = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{40})
			secondResumer := requireYieldError(t, err).Resumer()

			_, err = secondResumer.Resume(experimental.WithYielder(ctx), []uint64{2})
			require.EqualError(t, err, "cannot resume: expected 2 host results, but got 1")

			results, err := secondResumer.Resume(experimental.WithYielder(ctx), []uint64{20, 22})
			require.NoError(t, err)
			require.Zero(t, len(results))
		})
	}
}

func TestYield_ResumeUsesResumedTrapObserver(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			initialObserver := &recordingTrapObserver{}
			_, err := mod.ExportedFunction("run_twice").Call(
				experimental.WithTrapObserver(experimental.WithYielder(ctx), initialObserver),
			)
			resumer := requireYieldError(t, err).Resumer()

			resumeObserver := &recordingTrapObserver{}
			resumeCtx := experimental.WithTrapObserver(
				experimental.WithHostCallPolicy(
					experimental.WithYielder(ctx),
					experimental.HostCallPolicyFunc(func(context.Context, api.Module, api.FunctionDefinition) bool {
						return false
					}),
				),
				resumeObserver,
			)

			_, err = resumer.Resume(resumeCtx, []uint64{1})
			require.True(t, errors.Is(err, wasmruntime.ErrRuntimePolicyDenied), "expected ErrRuntimePolicyDenied, got %v", err)
			require.Zero(t, initialObserver.count())

			observation := resumeObserver.single(t)
			require.Equal(t, experimental.TrapCausePolicyDenied, observation.Cause)
			require.True(t, errors.Is(observation.Err, wasmruntime.ErrRuntimePolicyDenied))
			require.Equal(t, mod.Name(), observation.Module.Name())
		})
	}
}

func TestYield_ConcurrentResumePanicsSecondCaller(t *testing.T) {
	type resumeOutcome struct {
		results  []uint64
		err      error
		panicErr error
	}

	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			resumer := requireYieldError(t, err).Resumer()

			start := make(chan struct{})
			outcomes := make(chan resumeOutcome, 2)

			for i := 0; i < 2; i++ {
				go func() {
					<-start
					var outcome resumeOutcome
					outcome.panicErr = require.CapturePanic(func() {
						outcome.results, outcome.err = resumer.Resume(experimental.WithYielder(ctx), []uint64{7})
					})
					outcomes <- outcome
				}()
			}

			close(start)
			first := <-outcomes
			second := <-outcomes

			var panicOutcome, successOutcome resumeOutcome
			switch {
			case first.panicErr != nil && second.panicErr == nil:
				panicOutcome, successOutcome = first, second
			case second.panicErr != nil && first.panicErr == nil:
				panicOutcome, successOutcome = second, first
			default:
				t.Fatalf("expected one panic and one success, got first=%+v second=%+v", first, second)
			}

			require.Contains(t, panicOutcome.panicErr.Error(), "Resume called more than once")
			require.NoError(t, successOutcome.err)
			require.Equal(t, []uint64{107}, successOutcome.results)
		})
	}
}

func TestYieldObserver_Lifecycle(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			provider := newObservingTimeProvider()
			mod, rt, ctx := setupYieldTest(t, ec.cfg.WithTimeProvider(provider))
			defer rt.Close(ctx)

			observer := &recordingYieldObserver{}
			_, err := mod.ExportedFunction("run").Call(
				experimental.WithYieldObserver(experimental.WithYielder(ctx), observer),
			)
			resumer := requireYieldError(t, err).Resumer()

			results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.NoError(t, err)
			require.Equal(t, []uint64{142}, results)

			observations := observer.snapshot()
			require.Equal(t, 2, len(observations))
			require.Equal(t, experimental.YieldEventYielded, observations[0].Event)
			require.Equal(t, uint64(1), observations[0].YieldCount)
			require.Equal(t, 1, observations[0].ExpectedHostResults)
			require.Equal(t, int64(0), observations[0].SuspendedNanos)
			require.Equal(t, experimental.YieldEventResumed, observations[1].Event)
			require.Equal(t, uint64(1), observations[1].YieldCount)
			require.Equal(t, 1, observations[1].ExpectedHostResults)
			require.Equal(t, int64(1_000_000), observations[1].SuspendedNanos)
		})
	}
}

func TestYieldObserver_Cancel(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			provider := newObservingTimeProvider()
			mod, rt, ctx := setupYieldTest(t, ec.cfg.WithTimeProvider(provider))
			defer rt.Close(ctx)

			observer := &recordingYieldObserver{}
			_, err := mod.ExportedFunction("run").Call(
				experimental.WithYieldObserver(experimental.WithYielder(ctx), observer),
			)
			resumer := requireYieldError(t, err).Resumer()

			resumer.Cancel()
			resumer.Cancel()

			observations := observer.snapshot()
			require.Equal(t, 2, len(observations))
			require.Equal(t, experimental.YieldEventYielded, observations[0].Event)
			require.Equal(t, experimental.YieldEventCancelled, observations[1].Event)
			require.Equal(t, uint64(1), observations[1].YieldCount)
			require.Equal(t, 1, observations[1].ExpectedHostResults)
			require.Equal(t, int64(1_000_000), observations[1].SuspendedNanos)
		})
	}
}

func TestYieldObserver_ReyieldAndValidation(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			provider := newObservingTimeProvider()
			mod, rt, ctx := setupYieldTest(t, ec.cfg.WithTimeProvider(provider))
			defer rt.Close(ctx)

			observer := &recordingYieldObserver{}

			_, err := mod.ExportedFunction("run").Call(
				experimental.WithYieldObserver(experimental.WithYielder(ctx), observer),
			)
			resumer := requireYieldError(t, err).Resumer()

			_, err = resumer.Resume(experimental.WithYielder(ctx), nil)
			require.EqualError(t, err, "cannot resume: expected 1 host results, but got 0")
			require.Equal(t, 1, len(observer.snapshot()))

			_, err = mod.ExportedFunction("run_twice").Call(
				experimental.WithYieldObserver(experimental.WithYielder(ctx), observer),
			)
			firstResumer := requireYieldError(t, err).Resumer()

			_, err = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{40})
			secondYield := requireYieldError(t, err)

			results, err := secondYield.Resumer().Resume(experimental.WithYielder(ctx), []uint64{2})
			require.NoError(t, err)
			require.Equal(t, []uint64{42}, results)

			observations := observer.snapshot()
			require.Equal(t, 5, len(observations))
			require.Equal(t, experimental.YieldEventYielded, observations[0].Event)
			require.Equal(t, experimental.YieldEventYielded, observations[1].Event)
			require.Equal(t, uint64(1), observations[1].YieldCount)
			require.Equal(t, experimental.YieldEventResumed, observations[2].Event)
			require.Equal(t, uint64(1), observations[2].YieldCount)
			require.Equal(t, experimental.YieldEventYielded, observations[3].Event)
			require.Equal(t, uint64(2), observations[3].YieldCount)
			require.Equal(t, experimental.YieldEventResumed, observations[4].Event)
			require.Equal(t, uint64(2), observations[4].YieldCount)
		})
	}
}

func TestYield_WithoutEnable(t *testing.T) {
	ctx := context.Background()
	if got := experimental.GetYielder(ctx); got != nil {
		t.Fatal("expected nil yielder when not enabled")
	}
}

func TestYield_ErrorIsYielded(t *testing.T) {
	ye := experimental.NewYieldError(nil)
	if !errors.Is(ye, experimental.ErrYielded) {
		t.Fatal("errors.Is(YieldError, ErrYielded) should be true")
	}
}

func yieldDifferentResultCountsWasm() []byte {
	return binaryencoding.EncodeModule(&wasm.Module{
		TypeSection: []wasm.FunctionType{
			{Results: []api.ValueType{api.ValueTypeI32}},
			{Results: []api.ValueType{api.ValueTypeI32, api.ValueTypeI32}},
			{},
		},
		ImportSection: []wasm.Import{
			{Module: "example", Name: "async_one", Type: wasm.ExternTypeFunc, DescFunc: 0},
			{Module: "example", Name: "async_two", Type: wasm.ExternTypeFunc, DescFunc: 1},
		},
		FunctionSection: []wasm.Index{2},
		CodeSection: []wasm.Code{{
			Body: []byte{
				wasm.OpcodeCall, 0,
				wasm.OpcodeDrop,
				wasm.OpcodeCall, 1,
				wasm.OpcodeDrop,
				wasm.OpcodeDrop,
				wasm.OpcodeEnd,
			},
		}},
		ExportSection: []wasm.Export{{Type: api.ExternTypeFunc, Name: "run", Index: 2}},
	})
}
