package experimental_test

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"log"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"
	"github.com/tetratelabs/wazero/experimental"
)

// yieldExampleWasm was generated by the following:
//
//	cd testdata; wasm-tools parse yield.wat -o yield.wasm
//
//go:embed testdata/yield.wasm
var yieldExampleWasm []byte

// Example_enableYielder demonstrates using the experimental async
// yield/resume API to cooperatively suspend Wasm execution during a
// host function call, allowing the host to perform asynchronous work
// and later resume the module from any goroutine.
//
// The Wasm module imports a host function "async_work" that yields
// immediately. The embedder receives a Resumer via a *YieldError,
// supplies the host function's return value through Resume, and
// the module finishes its computation (adding 100 to the result).
//
// While the call is suspended, that exported function call remains in-flight:
// do not call it again until the returned Resumer has been resumed or
// cancelled.
func Example_enableYielder() {
	ctx := context.Background()

	rt := wazero.NewRuntime(ctx)
	defer rt.Close(ctx) // This closes everything this Runtime created.

	// Register a host function that yields execution. In a real application
	// this would initiate asynchronous work (e.g., a network call) and the
	// result would be provided later via Resume.
	_, err := rt.NewHostModuleBuilder("example").
		NewFunctionBuilder().
		WithGoModuleFunction(api.GoModuleFunc(func(ctx context.Context, mod api.Module, stack []uint64) {
			// GetYielder returns non-nil because we called WithYielder below.
			yielder := experimental.GetYielder(ctx)
			if yielder == nil {
				log.Panicln("yield not enabled")
			}

			// Yield suspends Wasm execution. Code after this is unreachable.
			// The host function's return value will be provided via Resume.
			yielder.Yield()
		}), nil, []api.ValueType{api.ValueTypeI32}).
		Export("async_work").
		Instantiate(ctx)
	if err != nil {
		log.Panicln(err)
	}

	mod, err := rt.Instantiate(ctx, yieldExampleWasm) // Instantiate the Wasm code
	if err != nil {
		log.Panicln(err)
	}

	// Enable yields by wrapping the context with WithYielder.
	yieldCtx := experimental.WithYielder(ctx)

	// Call the exported "run" function. It will call async_work which yields.
	_, err = mod.ExportedFunction("run").Call(yieldCtx)

	// The error is a *YieldError carrying a Resumer.
	var yieldErr *experimental.YieldError
	if !errors.As(err, &yieldErr) {
		log.Panicln("expected YieldError, got:", err)
	}

	// At this point no goroutine is blocked. The embedder is free to do
	// async work, schedule on a different goroutine, etc. The suspended call
	// is still outstanding until Resume or Cancel completes it.

	// Resume execution, providing 42 as the host function's return value.
	// The Wasm function "run" adds 100 to whatever async_work returns.
	results, err := yieldErr.Resumer().Resume(experimental.WithYielder(ctx), []uint64{42})
	if err != nil {
		log.Panicln(err)
	}

	fmt.Println(results[0]) // 42 + 100 = 142
	// Output:
	// 142
}
