package experimental_test

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"sync"
	"testing"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"
	"github.com/tetratelabs/wazero/experimental"
	"github.com/tetratelabs/wazero/internal/testing/require"
)

// yieldWasm was generated by the following:
//
//	cd testdata; wasm-tools parse yield.wat -o yield.wasm
//
//go:embed testdata/yield.wasm
var yieldWasm []byte

type engineConfig struct {
	name string
	cfg  wazero.RuntimeConfig
}

func engineConfigs() []engineConfig {
	return []engineConfig{
		{"interpreter", wazero.NewRuntimeConfigInterpreter()},
		{"compiler", wazero.NewRuntimeConfigCompiler()},
	}
}

// yieldingHostFunc is a GoModuleFunction that yields execution.
type yieldingHostFunc struct{ t *testing.T }

func (f *yieldingHostFunc) Call(ctx context.Context, mod api.Module, stack []uint64) {
	yielder := experimental.GetYielder(ctx)
	if yielder == nil {
		f.t.Fatal("expected yielder in context")
	}
	yielder.Yield()
	// Unreachable after Yield().
}

func setupYieldTest(t *testing.T, cfg wazero.RuntimeConfig) (api.Module, wazero.Runtime, context.Context) {
	return setupYieldTestWithHost(t, cfg, &yieldingHostFunc{t: t})
}

func setupYieldTestWithHost(t *testing.T, cfg wazero.RuntimeConfig, host api.GoModuleFunction) (api.Module, wazero.Runtime, context.Context) {
	t.Helper()
	ctx := context.Background()
	rt := wazero.NewRuntimeWithConfig(ctx, cfg)

	_, err := rt.NewHostModuleBuilder("example").
		NewFunctionBuilder().
		WithGoModuleFunction(host,
			nil,                                // no params
			[]api.ValueType{api.ValueTypeI32}). // 1 i32 result
		Export("async_work").
		Instantiate(ctx)
	require.NoError(t, err)

	mod, err := rt.Instantiate(ctx, yieldWasm)
	require.NoError(t, err)

	return mod, rt, ctx
}

func requireYieldError(t *testing.T, err error) *experimental.YieldError {
	t.Helper()
	var yieldErr *experimental.YieldError
	require.True(t, errors.As(err, &yieldErr), "expected YieldError, got: %v", err)
	require.NotNil(t, yieldErr.Resumer())
	return yieldErr
}

func TestYield_BasicYieldAndResume(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)
			resumer := yieldErr.Resumer()

			results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.NoError(t, err)
			require.Equal(t, uint64(142), results[0]) // 42 + 100
		})
	}
}

func TestYield_ResumeFromDifferentGoroutine(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)

			var wg sync.WaitGroup
			var results []uint64
			var resumeErr error
			wg.Add(1)
			go func() {
				defer wg.Done()
				results, resumeErr = yieldErr.Resumer().Resume(experimental.WithYielder(ctx), []uint64{7})
			}()
			wg.Wait()

			require.NoError(t, resumeErr)
			require.Equal(t, uint64(107), results[0]) // 7 + 100
		})
	}
}

func TestYield_Cancel(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			yieldCtx := experimental.WithYielder(ctx)
			_, err := mod.ExportedFunction("run").Call(yieldCtx)

			yieldErr := requireYieldError(t, err)
			resumer := yieldErr.Resumer()

			resumer.Cancel()
			resumer.Cancel() // idempotent

			_, err = resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.Error(t, err)
			require.Contains(t, err.Error(), "cancelled")
		})
	}
}

func TestYield_ResumeRejectsWrongHostResultCount(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			for _, tc := range []struct {
				name        string
				hostResults []uint64
			}{
				{name: "too few", hostResults: nil},
				{name: "too many", hostResults: []uint64{1, 2}},
			} {
				t.Run(tc.name, func(t *testing.T) {
					mod, rt, ctx := setupYieldTest(t, ec.cfg)
					defer rt.Close(ctx)

					_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
					resumer := requireYieldError(t, err).Resumer()

					_, err = resumer.Resume(experimental.WithYielder(ctx), tc.hostResults)
					require.EqualError(t, err, fmt.Sprintf("cannot resume: expected 1 host results, but got %d", len(tc.hostResults)))

					results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
					require.NoError(t, err)
					require.Equal(t, []uint64{142}, results)
				})
			}
		})
	}
}

func TestYield_ResumeRejectsNilContext(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			resumer := requireYieldError(t, err).Resumer()

			_, err = resumer.Resume(nil, []uint64{42})
			require.EqualError(t, err, "cannot resume: context is nil")

			results, err := resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.NoError(t, err)
			require.Equal(t, []uint64{142}, results)
		})
	}
}

func TestYield_ResumeRejectsClosedModule(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run").Call(experimental.WithYielder(ctx))
			resumer := requireYieldError(t, err).Resumer()

			require.NoError(t, mod.Close(ctx))

			_, err = resumer.Resume(experimental.WithYielder(ctx), []uint64{42})
			require.ErrorIs(t, err, api.NewExitError(0))
		})
	}
}

func TestYield_ReyieldUsesFreshResumer(t *testing.T) {
	for _, ec := range engineConfigs() {
		t.Run(ec.name, func(t *testing.T) {
			mod, rt, ctx := setupYieldTest(t, ec.cfg)
			defer rt.Close(ctx)

			_, err := mod.ExportedFunction("run_twice").Call(experimental.WithYielder(ctx))
			firstResumer := requireYieldError(t, err).Resumer()

			_, err = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{40})
			secondYield := requireYieldError(t, err)

			firstResumer.Cancel() // spent resumers must not interfere with the new suspended execution

			results, err := secondYield.Resumer().Resume(experimental.WithYielder(ctx), []uint64{2})
			require.NoError(t, err)
			require.Equal(t, []uint64{42}, results)

			panicErr := require.CapturePanic(func() {
				_, _ = firstResumer.Resume(experimental.WithYielder(ctx), []uint64{1})
			})
			require.Error(t, panicErr)
			require.Contains(t, panicErr.Error(), "Resume called more than once")
		})
	}
}

func TestYield_WithoutEnable(t *testing.T) {
	ctx := context.Background()
	if got := experimental.GetYielder(ctx); got != nil {
		t.Fatal("expected nil yielder when not enabled")
	}
}

func TestYield_ErrorIsYielded(t *testing.T) {
	ye := experimental.NewYieldError(nil)
	if !errors.Is(ye, experimental.ErrYielded) {
		t.Fatal("errors.Is(YieldError, ErrYielded) should be true")
	}
}
